/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Head2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function GhostModel(props) {
  const { nodes, materials } = useGLTF('/models/Head2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.berd_000_umodel.geometry} material={materials.berd_diff_000_a_uni} />
      <mesh geometry={nodes.berd_000_umodel002.geometry} material={materials['berd_diff_000_a_uni.002']} />
    </group>
  )
}

useGLTF.preload('/models/Head2.glb')
